[workspace]
resolver = "3"
members = ["apps/cli", "crates/w3"]

[workspace.package]
edition = "2024"
version = "0.1.0-alpha.0"
license = "MIT"
repository = "https://github.com/azataiot/w3"
homepage = "https://github.com/azataiot/w3"

[workspace.dependencies]
w3 = { path = "crates/w3", version = "0.1.0-alpha.0" }

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dist]
inherits = "release"
lto = "thin"
